
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'O \x8c\xb1\xf7I]\xc2\x8e\xf3W\xad\xd6s\xb4X'
    
_lr_action_items = {'H2':([0,12,],[2,2,]),'H3':([0,12,],[3,3,]),'H1':([0,12,],[4,4,]),'TEXT':([2,3,4,6,],[8,8,8,8,]),'CR':([5,7,8,9,10,11,14,15,],[12,-2,-8,-5,-6,-4,-3,-7,]),'STRONG':([0,8,12,13,],[6,-8,6,15,]),'$end':([1,5,7,8,9,10,11,14,15,],[0,-1,-2,-8,-5,-6,-4,-3,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([0,],[1,]),'expression':([0,12,],[7,14,]),'statement':([0,],[5,]),'factor':([2,3,4,6,],[9,10,11,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> body","S'",1,None,None,None),
  ('body -> statement','body',1,'p_body','main.py',48),
  ('statement -> expression','statement',1,'p_state','main.py',52),
  ('statement -> statement CR expression','statement',3,'p_state','main.py',53),
  ('expression -> H1 factor','expression',2,'p_exp_cr','main.py',60),
  ('expression -> H2 factor','expression',2,'p_exp_cr','main.py',61),
  ('expression -> H3 factor','expression',2,'p_exp_cr','main.py',62),
  ('expression -> STRONG factor STRONG','expression',3,'p_exp_strong','main.py',71),
  ('factor -> TEXT','factor',1,'p_factor_text','main.py',75),
]
